### ISSUE TITLE
Unable to install module "report_py3o" because an external dependency is not met: No module named py3o.template

### ISSUE THREAD

**Issue by diezcode** [akretion/odoo-py3o-report-templates#3]
Installed the dependencies like this:

```
pip install py3o.template
pip install py3o.formats
```

pip3 because of odoo12 running on python3
```
pip3 install py3o.template
pip3 install py3o.formats
```

still getting the error when I try to install the py3o report modul.
any input or fix?

thank you :)

**Comment by diezcode** [comment]
```
pip3 install py3o.formats
Collecting py3o.formats
  Using cached https://files.pythonhosted.org/packages/75/db/dd583bb4d89c7bfa4b41674e20ef2e2da4f62501b56cf502b2251c940082/py3o.formats-0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 11, in <module>
        from setuptools.extern.six.moves import filterfalse, map
      File "/usr/lib/python3/dist-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
        @_call_aside
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
        f(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
        add_activation_listener(lambda dist: dist.activate())
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 956, in subscribe
        callback(dist)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2515, in activate
        declare_namespace(pkg)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lezf3nx5/py3o.formats/

```

**Comment by bealdav** [comment]
It works for me

pip 19

ubunbu 18.04

```
$ pip3 install py3o.formats --user
Collecting py3o.formats
Requirement already satisfied: setuptools in /home/dav/.local/lib/python3.6/site-packages (from py3o.formats) (41.0.1)
Installing collected packages: py3o.formats
Successfully installed py3o.formats-0.3

$ pip3 show py3o.formats
Name: py3o.formats
Version: 0.3
Summary: Formats declarations for py3o
Home-page: http://bitbucket.org/faide/py3o.formats
Author: Björn Ricks
Author-email: bjoern.ricks@gmail.com
License: MIT License
Location: /home/dav/.local/lib/python3.6/site-packages
Requires: setuptools
Required-by:  
```
